In [4]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

In [7]:
#Question1:
#Amswer:
#list_: It is a Python list containing string elements.
#array_list: It is a NumPy array that was created using the np.array() function.
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [15]:
#Question2:
#Answer:
print("Data types of each element in list_")
for i in list_:
    print(f"{i}: {type(i)}")
    print("Data types of each element in array_list")
for j in array_list:
    print(f"{j}: {type(j)}")

Data types of each element in list_
1: <class 'str'>
Data types of each element in array_list
2: <class 'str'>
Data types of each element in array_list
3: <class 'str'>
Data types of each element in array_list
4: <class 'str'>
Data types of each element in array_list
5: <class 'str'>
Data types of each element in array_list
1: <class 'numpy.str_'>
2: <class 'numpy.str_'>
3: <class 'numpy.str_'>
4: <class 'numpy.str_'>
5: <class 'numpy.str_'>


In [16]:
#Question3:
#Answer:
array_list = np.array(object = list_, dtype = int)

In [19]:
array_list.dtype

dtype('int64')

In [22]:
type(list_)

list

In [23]:
print("Data types of each element in list_")
for i in list_:
    print(f"{i}: {type(i)}")
    print("Data types of each element in array_list")
for j in array_list:
    print(f"{j}: {type(j)}")

Data types of each element in list_
1: <class 'str'>
Data types of each element in array_list
2: <class 'str'>
Data types of each element in array_list
3: <class 'str'>
Data types of each element in array_list
4: <class 'str'>
Data types of each element in array_list
5: <class 'str'>
Data types of each element in array_list
1: <class 'numpy.int64'>
2: <class 'numpy.int64'>
3: <class 'numpy.int64'>
4: <class 'numpy.int64'>
5: <class 'numpy.int64'>


In [24]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [25]:
#Question4:
#Answer:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.shape(num_array)

(2, 3)

In [27]:
np.size(num_array)

6

In [54]:
#Question5:
#Answer:
mat = np.array([[0,0,0],[0,0,0],[0,0,0]])

In [55]:
np.shape(mat)

(3, 3)

In [56]:
np.size(mat)

9

In [57]:
mat

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [58]:
#method2

In [60]:
mat1 = np.zeros([3,3])

In [61]:
mat

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [62]:
np.shape(mat1)

(3, 3)

In [63]:
np.size(mat1)

9

In [64]:
#Question6:
#Answer:
identity_matrix = np.eye(5)

In [65]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])